name: just_make_logo
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0

environment:
  sdk: ^3.9.2

dependencies:
  cupertino_icons: ^1.0.8
  file_picker: ^8.0.0
  flutter:
    sdk: flutter
  flutter_dropdown_button: ^1.6.1
  google_fonts: ^6.2.1
  image: ^4.5.0
  flutter_riverpod: ^2.6.1
  riverpod_annotation: ^2.6.1
  shared_preferences: ^2.5.4
dev_dependencies:
  build_runner: ^2.5.4
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  flutter_tweakcn_generator: ^0.2.3
  riverpod_generator: ^2.6.5
  riverpod_lint: ^2.6.5

flutter:
  uses-material-design: true
